## Python 202

**Scenario:** Today we are going to build upon the for loops of yesterday. Who has ever got to the cash register at costco, or whole foods, seen the total and asked "how did I spend that much?". Today we have a grocery list of items and prices, but we do not have infinite money (unfortunately), so we need to have a program that will look at our grocery list and help us manage our shopping and cost.

### Learning goals:

Today we will:
 - revisit what for loop does, using a dictionary
 - use `break` to adjust loop activity
 - use nested loops to navigate a nested dictionary
 - write a robust function that will take any nested dictionary of items, costs, and print out your shopping list, stopping when the total cost gets to high, and telling you the average cost per item in your cart.

Let's revisit what a for loop does. Here we have a list of items, and a separate list of costs. We are going to write a loop to print each item, it's cost, and the total of our grocery list.

```
items = ['cheese', 'whole milk', 'kefir', 'tofu four-pack', 'kale', 'oranges', 'ham', 'ben & jerry's']
cost = [2.79, 3.42, 4.50, 12.00, 2.75, 3.64, 25.00, 5.29]
```

![groc-cart](https://images.pexels.com/photos/1389103/pexels-photo-1389103.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260)

### For loops:
First, let's create a for-loop that prints each item in the list with "I need to buy: " item.

In [7]:
items = ['cheese', 'whole milk', 'kefir', 'tofu four-pack', 'kale', 'oranges', 'ham', 'ben & jerrys']
         
print("I need to buy: " + "," .join(items[:-1])+ " and, " + items[-1]+".")


I need to buy: cheese,whole milk,kefir,tofu four-pack,kale,oranges,ham and, ben & jerrys.


Let's make that a little nicer looking:

```
print("I need to buy: ")
for item in items:
   print(" - [ ] ", item)
```

Okay, we want to work through a dictionary, so what's one way to convert those two lists to a dictionary?

_Hint_: Check [this](https://www.w3schools.com/python/ref_func_zip.asp) documentation. 

In [12]:
print ("I need to buy: ")
for item in items:
        print (" - [] " . item)

I need to buy: 


AttributeError: 'str' object has no attribute 'item'

In [13]:
cost = [2.79, 3.42, 4.50, 12.00, 2.75, 3.64, 25.00, 5.29]
items_cost = dict(zip(items,cost))
print("I need to buy: ")
for key, value in items_cost.items():
    print("-[]",key, ": for $", value)
#if some keys were dropped out, then the list will only be as long as the shortest list of keys?
#zip is making a new item

I need to buy: 
-[] cheese : for $ 2.79
-[] whole milk : for $ 3.42
-[] kefir : for $ 4.5
-[] tofu four-pack : for $ 12.0
-[] kale : for $ 2.75
-[] oranges : for $ 3.64
-[] ham : for $ 25.0
-[] ben & jerrys : for $ 5.29


In [ ]:
items_cost = dict(zip)

So let's now add the total grocery bill at the end:

In [14]:
print("I need to buy: ")
total_cost = 0

for key, value in items_cost.items():
    print("-[]",key, ": for $", value)
    total_cost = total_cost+value
    
print("total cost is: $", total_cost)

#each time you have these pairs, add the value to your cost each time

I need to buy: 
-[] cheese : for $ 2.79
-[] whole milk : for $ 3.42
-[] kefir : for $ 4.5
-[] tofu four-pack : for $ 12.0
-[] kale : for $ 2.75
-[] oranges : for $ 3.64
-[] ham : for $ 25.0
-[] ben & jerrys : for $ 5.29
total cost is: $ 59.39


In [16]:
#other way to do it....technically more concise with long lists:

print("I need to buy: ")

for key, value in items_cost.items():
    print("-[]",key, ": for $", value)
    total_cost = total_cost+value
    
print("total cost is: $", sum(items_cost.values()))

I need to buy: 
-[] cheese : for $ 2.79
-[] whole milk : for $ 3.42
-[] kefir : for $ 4.5
-[] tofu four-pack : for $ 12.0
-[] kale : for $ 2.75
-[] oranges : for $ 3.64
-[] ham : for $ 25.0
-[] ben & jerrys : for $ 5.29
total cost is: $ 59.39


In [ ]:
#yet another way to do it....technically more concise with long lists:

??

Does this look reasonable?

What if you only had $25? 

How can you build it out to stop adding items when the total is over $25?

### While, break, and continue
What does a while loop look like in Python?

In [17]:
i = 1
while i < 6:
  print(i)
  i += 1

1
2
3
4
5


- What is break and continue?  
- Are they different? How?
- Run the following code:

In [18]:
i = 0
while i < 6:
  i += 1
  if i == 3:
    print("foo")
    continue
  print(i)
#continue is "keep going"; it goes back to the while loop

1
2
foo
4
5
6


How does the code above work?

Now run this code:

In [19]:
i = 0
while i < 6:
  i += 1
  if i == 3:
    print("foo")
    break
  print(i)
#it goes into the while loop, increments by 1; when it gets to 3 it prints foo and then stops the for loop

1
2
foo


Why is the output different?

It stopped at foo, why?

We can also include `breaks` in for-loops.

What would we use to **stop** the for loop if the total reached $25?

In [23]:
print("I need to buy: ")

total_cost=0
for key,value in items_cost.items():
    if total_cost+value>=25:
        break
    print("-[]",key, ": for $", value)
    total_cost += value
    
print("total cost is: $", total_cost)

#

I need to buy: 
-[] cheese : for $ 2.79
-[] whole milk : for $ 3.42
-[] kefir : for $ 4.5
-[] tofu four-pack : for $ 12.0
total cost is: $ 22.71


What if we wanted to use continue and break to stop the program if an item costs more than **$10** ?

In [24]:
print("I need to buy: ")

total_cost=0
for key,value in items_cost.items():
    if value > 10:
        continue
    print("-[]",key, ": for $", value)
    total_cost += value
    
print("total cost is: $", total_cost)



I need to buy: 
-[] cheese : for $ 2.79
-[] whole milk : for $ 3.42
-[] kefir : for $ 4.5
-[] kale : for $ 2.75
-[] oranges : for $ 3.64
-[] ben & jerrys : for $ 5.29
total cost is: $ 22.39


### Nested Loops

In [25]:
listx = [1,2,3,4,5]

for x in listx:
  print('loop1:', x)
  for y in listx:
    print('loop2---', y)
#here you're referencing the same list, and then going through it in a loop and nesting it

loop1: 1
loop2--- 1
loop2--- 2
loop2--- 3
loop2--- 4
loop2--- 5
loop1: 2
loop2--- 1
loop2--- 2
loop2--- 3
loop2--- 4
loop2--- 5
loop1: 3
loop2--- 1
loop2--- 2
loop2--- 3
loop2--- 4
loop2--- 5
loop1: 4
loop2--- 1
loop2--- 2
loop2--- 3
loop2--- 4
loop2--- 5
loop1: 5
loop2--- 1
loop2--- 2
loop2--- 3
loop2--- 4
loop2--- 5


What do you expect to see? Why?

Here's a more complicated example, what is it doing?

In [26]:
i = 2
while(i < 100):
   j = 2
   while(j <= (i/j)):
      if not(i%j): break
      j = j + 1
   if (j > i/j) : print( i, " is prime")
   i = i + 1

print ("Good bye!")

2  is prime
3  is prime
5  is prime
7  is prime
11  is prime
13  is prime
17  is prime
19  is prime
23  is prime
29  is prime
31  is prime
37  is prime
41  is prime
43  is prime
47  is prime
53  is prime
59  is prime
61  is prime
67  is prime
71  is prime
73  is prime
79  is prime
83  is prime
89  is prime
97  is prime
Good bye!


Here is a more robust shopping list of nested dictionaries:
```
shopping_dict = {'Groceries': {'ben & jerrys': 5.29, 'cheese': 2.79,'ham': 25.0, 'kale': 2.75,'kefir': 4.5,'oranges': 3.64,'tofu four-pack': 12.0,'whole milk': 3.42},
                 'House supplies': {'toilet paper pack': 16.50, 'clorox spray': 6.43, 'kleenex': 2.50,},
                 'Pet supplies': {'Taste of the Wild': 65.20, 'squeaky toy': 4.50, 'duck feet': 8.45}}
```

write the nested for loops to print out each grocery list with its total

_Hint_

- use [this link](https://pyformat.info/#number) for help in formatting the total to two decimal places

In [30]:
shopping_dict = {'Groceries': {'ben & jerrys': 5.29, 'cheese': 2.79,'ham': 25.0, 'kale': 2.75,'kefir': 4.5,'oranges': 3.64,'tofu four-pack': 12.0,'whole milk': 3.42},
                 'House supplies': {'toilet paper pack': 16.50, 'clorox spray': 6.43, 'kleenex': 2.50,},
                 'Pet supplies': {'Taste of the Wild': 65.20, 'squeaky toy': 4.50, 'duck feet': 8.45}}


In [43]:
###### OUR SOLUTION (correct, but maybe not the most sophisticated:)

##def print_shopping(sample_dict)
print("I need to buy: ")

##replace shopping_dict with sample_dict so it can use any dictioanry, not specifically shopping_dict
for cat in (shopping_dict.keys()):
    print (cat + ":")
    for item,value in shopping_dict[cat].items():
        total_cost += value
        print("\t" + "-[]"+item+str(value)) 
    
print("Total cost is: $", total_cost)


I need to buy: 
Groceries:
	-[]ben & jerrys5.29
	-[]cheese2.79
	-[]ham25.0
	-[]kale2.75
	-[]kefir4.5
	-[]oranges3.64
	-[]tofu four-pack12.0
	-[]whole milk3.42
House supplies:
	-[]toilet paper pack16.5
	-[]clorox spray6.43
	-[]kleenex2.5
Pet supplies:
	-[]Taste of the Wild65.2
	-[]squeaky toy4.5
	-[]duck feet8.45
total cost is: $ 185.36


In [ ]:
#### instructor solution:??
total_bill = 0
for key, values in shopping_dict.items():
    print(key)

for aisle,shelf in values.items():
    print("-[]--")
    total_bill= total_bill + shelf
    
print("Total cost is: $", total_cost)

In [37]:
list
##note: make sure you are not using reserved keywords!

[1, 2, 3, 4, 5]

In [35]:
### note: brainstorming 
for cat, value in (shopping_dict.items()):
    print (cat,value)
#just as an example: this would allow you to print everything, not just the key

Groceries {'ben & jerrys': 5.29, 'cheese': 2.79, 'ham': 25.0, 'kale': 2.75, 'kefir': 4.5, 'oranges': 3.64, 'tofu four-pack': 12.0, 'whole milk': 3.42}
House supplies {'toilet paper pack': 16.5, 'clorox spray': 6.43, 'kleenex': 2.5}
Pet supplies {'Taste of the Wild': 65.2, 'squeaky toy': 4.5, 'duck feet': 8.45}


In [ ]:
##notes:  
#to round to two decimal spaces:  {a:..2f}.format(a=v)) --> for formatting
# \t is a tab, \n jump line

### Functions

**Built-in functions** <br>
Many useful functions are already built into Python:<br>

`print()`: print the given string or variable's value<br>
`type()`: returns the datatype of the argument<br>
`len()`: returns the length of an array<br>
`sum()`: returns the sum of the array's values<br>
`min()`: returns the smallest member of an array <br>
`max()`: returns the largest member of an array<br>


**Writing your own functions**

```
def sayHello():
  print("Hello!")
```
How do we run it?

```
sayHello()
```

Let's talk about arguments or parameters. Let's say we want to make this function more dynamic and print out whatever we want! How would we do that?
```
def shout(phrase):
  print(phrase + "!!!")
shout("oh hai")
```

In [44]:
def shout(phrase):
  print(phrase + "!!!")
shout("oh hai")

oh hai!!!


What if we don't pass in an argument? What happens?
Maybe we can establish a default value for the argument in case it isn't passed in.

```
def shout(phrase = "oh hai"):
  print(phrase + "!!!")

shout()
shout("bye")
```

In [45]:
def shout(phrase = "oh hai"):
  print(phrase + "!!!")
shout()
shout("bye")

oh hai!!!
bye!!!


What if we wanted to run a function, take it's output and put it in to another function?

```
def addOne(number):
  return number + 1

def timesFive(number):
  return number * 5

numberPlusOne = addOne(1)
answer = timesFive(numberPlusOne)
print(answer)
```

What will the above code return?

In [46]:
def addOne(number):
  return number + 1

def timesFive(number):
  return number * 5

numberPlusOne = addOne(1)
answer = timesFive(numberPlusOne)
print(answer)

10


Adapt your shopping list nested for-loop to be wrapped in a function you could call on any shopping list of nested dictionaries.

### Mathematical Notation and Measures of Central Tendency 

median vs mode vs mean<br>
What's the difference?


`samp_list = [1,1,1,1,2,2,2,3,3,10,44]`

How could you write a for loop to calculate the mean?

In [ ]:
samp_list = [1,1,1,1,2,2,2,3,3,10,44]
# mode = most frequent variable = 1 
# base python does not have an average or mean function, you have to create a function to do that. 
## if you want to save a function and re-use, you can save it as a python file and then 

### Integration

adapt your function to do the following:
- stop the nested loop if a grocery total goes over $30
- print out the average cost of per item in your cart